### ISSUE TITLE
About exemplars of the static branch

### ISSUE THREAD

**Issue by ohheysherry66** [VividLe/Online-Action-Detection#1]
Thank you for your excellent work! I would like to ask a question which is how can we get the exemplars of all categories, it seems like not be implemented in the codes. Thank you!

**Comment by VividLe** [comment]
Lately, I am a bit busy. I will update the code to generate exemplars at the end of March.

You can try it by yourself. Considering a category, please collect all features belong to this category, then perform K-Means.

**Comment by ohheysherry66** [comment]
> 

Thank you for your reply！

**Comment by VividLe** [comment]
The script to generate category exemplars is updated in `scripts/generate-exemplars.py`.

**Comment by ohheysherry66** [comment]
> The script to generate category exemplars is updated in `scripts/generate-exemplars.py`.
Excellent work！
