### ISSUE TITLE
Some Details of The Paper

### ISSUE THREAD

**Issue by Echo0125** [VividLe/Online-Action-Detection#2]
Hi, 
Thank you for sharing the code. When I was reading your papers, I met some problems~
In Tabel 4, I found that you write that given a one-minute video, the running time of extracting the RGB feature is 2.3 seconds; I wonder how you calculate the time? If it was the time cost by extracting feature that used Res-200?

**Comment by VividLe** [comment]
In Table 4, it takes 2.3 seconds to extract features from a one-minute video with ResNet-200 backbone, using the [temporal-segment-networks](https://github.com/yjxiong/temporal-segment-networks) repo.
