### ISSUE TITLE
Baidu Cloud

### ISSUE THREAD

**Issue by hanyunfei-622** [VividLe/Online-Action-Detection#3]
Excuse me, what is the extraction code of Baidu Cloud?

**Comment by VividLe** [comment]
The code is "cola", as shown in the README file.

**Comment by Chuttyboy** [comment]
hai @VividLe 

 unable to download files in cloud

**Comment by VividLe** [comment]
I check the cloud files and can download thems. Please try again.

https://pan.baidu.com/s/1U6G4h9JsSUXRUl7I79jEDg

code: cola

**Comment by dqj5182** [comment]
Can you upload it also on Google Drive? I cannot download the files either. The link keep requiring me to download BaiduNetDisk and login the system.

**Comment by dqj5182** [comment]
or could you send the files directly to my email? My email address is dqj5182@snu.ac.kr
