### ISSUE TITLE
the corresponding paper

### ISSUE THREAD

**Issue by WalterWangRevo** [VividLe/Online-Action-Detection#4]
Hi，I am searching the code of the paper ”Structured Attention Composition for Temporal Action Localization“ ，and the url provided by arXiv is linked to this project. But it seems no relation between the code and the paper.

**Comment by VividLe** [comment]
Sorry for the mistake. Here is the code for [Structured Attention Composition](https://github.com/VividLe/Structured-Attention-Composition). Thanks for your interest.
