### ISSUE TITLE
features of HDD and TV

### ISSUE THREAD

**Issue by tfka** [VividLe/Online-Action-Detection#5]
Thanks for sharing the code. Would you please provide the features of two other benchmarks or give some guidance to get the features.

**Comment by 007invictus** [comment]
I have the same question for author,could you please offer the code of feature extraction and the checkpoint of the model?

**Comment by zstarN70** [comment]
@007invictus I think the project might be able to help you : https://github.com/yjxiong/temporal-segment-networks

**Comment by sqiangcao99** [comment]
Hi, is sensor data(dimension=8) directly as input to the network, without extracting features?

**Comment by VividLe** [comment]
Yes, the sensor data is directly input to the network.
