### ISSUE TITLE
HDD dataset  visual features

### ISSUE THREAD

**Issue by pgupta119** [VividLe/Online-Action-Detection#6]
Hi @VividLe,

I have a honda driving dataset that has images  (3fps) and I would like to use only the RGB features or visual features of the honda dataset. How would it be possible?
I couldn't find the optical flow feature and am not sure how to get the dataset. 
My task is to reconstruct one modality from the other one using a share multimodal representation (sensor  and videos(images frames)

Thanks

**Comment by VividLe** [comment]
Colar only use sensor data on HDD dataset. I am not experienced about using RGB features. However, your schedule seems reasonable. Please try it.

**Comment by pgupta119** [comment]
okay, Thanks
