### ISSUE TITLE
The question about model precision

### ISSUE THREAD

**Issue by wss-xjtu** [VividLe/Online-Action-Detection#7]
I trained your model on my device with THUMOS dataset without any modification, but the mAP is only 65.39. Since there is a gap between this result and the validation result (66.91) of the model you posted, I wonder if you are using some tricks. If not, can it be understood that the gap is only due to equipment differences.

[Epoch-7] [IDU-kinetics] mAP: 0.6539
BaseballPitch: 0.4485
BasketballDunk: 0.8277
Billiards: 0.2734
CleanAndJerk: 0.7331
CliffDiving: 0.8972
CricketBowling: 0.4617
CricketShot: 0.3120
Diving: 0.8743
FrisbeeCatch: 0.4104
GolfSwing: 0.7853
HammerThrow: 0.8585
HighJump: 0.7666
JavelinThrow: 0.7920
LongJump: 0.8093
PoleVault: 0.9041
Shotput: 0.6848
SoccerPenalty: 0.4923
TennisSwing: 0.6288
ThrowDiscus: 0.6688
VolleyballSpiking: 0.4487

**Comment by wss-xjtu** [comment]
sorry，My trained model's performance should be [Epoch-2] [IDU-kinetics] mAP: 0.6558

**Comment by VividLe** [comment]
I conduct experiments with the released project. Although equipment differences can lead to the performance variation, in my experiments, the performance should be at least 66.3 mAP.

**Comment by wss-xjtu** [comment]
I am not questioning the veracity of your experimental results, your work is very innovative.
But when I was training OadTR, the mAP of the result was also lower than the data published in the paper.
Considering that Nvidia V100 graphics cards are used in the original OadTR, but my device is GeForce RTX 3090. In the absence of any modification, I think this difference in results can only be a device problem.
So, I would like to ask, which GPU are you using?

**Comment by VividLe** [comment]
I use 2080Ti.

**Comment by wss-xjtu** [comment]
Ok, I will further confirm whether the difference is from the hardware device. 

Thank you for your reply.
